### ISSUE TITLE
problem with pan

### ISSUE THREAD

**Issue by sadish-d** [see-mike-out/erie-web#1]
I was going through your paper and tried to edit the pan settings in the following interactive table, but it was not working.

```
https://see-mike-out.github.io/erie-editor/paper/#tab-grammar-walkthrough
```

I tried to follow the instructions in the documentation here:
```
https://see-mike-out.github.io/erie-documentation/docs/encoding/pan.html
```

I tried the following specifications (one with `"scale": {"range": [-1, 0, 1]}` and the other without it):
```
{
  "description": "A histogram of Miles_per_Gallon variable.",
  "data": {
    "url": "../data/cars.json"
  },
  "tone": {
    "continued": false
  },
  "encoding": {
    "time": {
      "field": "Miles_per_Gallon",
      "type": "quantitative",
      "bin": true,
      "scale": {
        "length": 4.5
      },
      "tick": {
        "interval": 0.5,
        "playAtTime0": true
      }
    },
    "pan": {
      "field": "Miles_per_Gallon",
      "type": "quantitative",
      "scale": {
        "range": [-1, 0, 1]
      }
    },
    "pitch": {
      "aggregate": "count",
      "type": "quantitative",
      "scale": {
        "polarity": "positive",
        "maxDistinct": true
      }
    }
  },
  "config": {
    "speechRate": 1.75,
    "skipDescription": true,
    "skipTitle": true
  }
}
```

and

```
{
  "description": "A histogram of Miles_per_Gallon variable.",
  "data": {
    "url": "../data/cars.json"
  },
  "tone": {
    "continued": false
  },
  "encoding": {
    "time": {
      "field": "Miles_per_Gallon",
      "type": "quantitative",
      "bin": true,
      "scale": {
        "length": 4.5
      },
      "tick": {
        "interval": 0.5,
        "playAtTime0": true
      }
    },
    "pan": {
      "field": "Miles_per_Gallon",
      "type": "quantitative",
    },
    "pitch": {
      "aggregate": "count",
      "type": "quantitative",
      "scale": {
        "polarity": "positive",
        "maxDistinct": true
      }
    }
  },
  "config": {
    "speechRate": 1.75,
    "skipDescription": true,
    "skipTitle": true
  }
}
```

**Comment by see-mike-out** [comment]
Hello @sadish-d,

Thank you for the interest in this project and the first issue! I really appreciate that. 

First, I fixed the code. There were some legacy codes that I haven't updated and some unexpected cases. It should work now with the new design spec.

Second, I suggest using the following spec. It is basically adding `"bin": true` to your `pan` channel definition. 

*Why* Otherwise, it will use the "Miles_per_Gallon" to group the dataset in addition to the existing bins. This means you will have bunch of overlaid sounds, (potentially) causing some additional audio effects. When sine waves are played together, they generate some modulation effects. 

```json
{
  "description": "A histogram of Miles_per_Gallon variable.",
  "data": {
    "url": "../data/cars.json"
  },
  "tone": {
    "continued": false
  },
  "encoding": {
    "time": {
      "field": "Miles_per_Gallon",
      "type": "quantitative",
      "bin": true,
      "scale": {
        "length": 4.5
      },
      "tick": {
        "interval": 0.5,
        "playAtTime0": true
      }
    },
    "pan": {
      "field": "Miles_per_Gallon",
      "type": "quantitative",
      "bin": true,
      "scale": {
        "range": [-1, 0, 1]
      }
    },
    "pitch": {
      "aggregate": "count",
      "type": "quantitative",
      "scale": {
        "polarity": "positive",
        "maxDistinct": true
      }
    }
  },
  "config": {
    "speechRate": 1.75,
    "skipDescription": true,
    "skipTitle": true
  }
}
```

If you have remaining questions or have an alternative idea about how the design spec should be in this case, please feel free to reach out to me again. We can have a discussion.

Thank you so much!

**Comment by see-mike-out** [comment]
I agree that the original spec indicates probably not a good design. Yet, I can think of case where someone would like to have a binned variable as an ordinal variable although in this case, the binned and unbinned ones are originating from the same variable. My principle is to not restrict possibilities so that people can explore what's possible, good, or bad using Erie.
